HTHAplication/Areas/Admin/Controllers/HangHoaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HTHApplication.Common;
using Models.Dao;
using Models.EF;
namespace HTHAplication.Areas.Admin.Controllers
{
    public class HangHoaController : BaseController
    {

        // GET: Admin/HangHoa

        public ActionResult Index(string masp, int page = 1, int pageSize = 9)
        {
            var dao = new HangHoaDao();
            var model = dao.ListAllPaging(masp, page, pageSize);
            ViewBag.masp = masp;
            return View(model);
        }
        [HttpGet]
        public ActionResult Create()
        {
            SetLoaiMH();
            SetMauSac();
            SetNuocSanXuat();
            SetDVT();
            return View();
        }
        [HttpDelete]
        public ActionResult Delete(string id)
        {
            var dao = new HangHoaDao();
            var model = dao.GetByID(id);
            if (model != null)
            {
                dao.Delete(model);
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(string id)
        {
            var dao = new HangHoaDao();
            var model = dao.GetByID(id);
            if (model != null)
            {
                SetLoaiMH(model.MaHH);
                SetMauSac(model.MauID);
                SetNuocSanXuat(model.NuocSXID);
                SetDVT(model.DVT);
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(HangHoa entity)
        {
            SetLoaiMH();
            SetMauSac();
            SetNuocSanXuat();
            SetDVT();
            if (ModelState.IsValid)
            {
                var dao = new HangHoaDao();
                var cauhinhID = new CauHinhIDDao();
                var chID = cauhinhID.GetValueByID(entity.LoaiMH);
                string maHH = CommonFunction.GeneratedID(entity.LoaiMH, chID.Value + 1);
                entity.MaHH = maHH;
                entity.SoLuong = 0;
                entity.Status = true;
                entity.CreatedDate = DateTime.Now;
                if (entity.Anh == null)
                {
                    entity.Anh = "/Data/images/no-image.jpg";
                }
                entity.CreateBy = Session["UserName"].ToString();
                dao.Insert(entity);
                cauhinhID.Update(entity.LoaiMH);//Tăng biến đếm
                SetAlert("Thêm hàng hóa thành công!", "success");
            }
            else
            {
                SetAlert("Lỗi thêm hàng hóa!", "error");
            }
            return View();

        }
        [HttpPost]
        public ActionResult Edit(HangHoa entity)
        {
            SetLoaiMH(entity.MaHH);
            SetMauSac(entity.MauID);
            SetNuocSanXuat(entity.NuocSXID);
            SetDVT(entity.DVT);
            if (ModelState.IsValid)
            {
                var dao = new HangHoaDao();
                entity.ModifiedBy = Session["UserName"].ToString();
                if (dao.Update(entity))
                {
                   return RedirectToAction("Index");                    
                }
                else
                {
                    SetAlert("Lỗi cập nhật hàng hóa!", "error");
                    return View(entity);
                }
            }
            else
            {
                SetAlert("Lỗi cập nhật hàng hóa!", "error");
                return View(entity);
            }


        }

        public void SetLoaiMH(string selectedId = null)
        {
            var dao = new LoaiMatHangDao();
            ViewBag.LoaiMH = new SelectList(dao.ListAll(), "ID", "Ten", selectedId);
        }
        public void SetNuocSanXuat(int? selectedId = null)
        {
            var dao = new NuocSanXuatDao();
            ViewBag.NuocSXID = new SelectList(dao.ListALl(), "ID", "Ten", selectedId);
        }
        public void SetMauSac(int? selectedId = null)
        {
            var dao = new MauSacDao();
            ViewBag.MauID = new SelectList(dao.ListAll(), "ID", "Ten", selectedId);
        }
        public void SetDVT(int? selectedId = null)
        {
            var dao = new DonViTinhDao();
            ViewBag.DVT = new SelectList(dao.ListAll(), "ID", "Ten", selectedId);
        }
    }
}

HTHAplication/Areas/Admin/Views/HangHoa/Create.cshtml
@model Models.EF.HangHoa

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@section header{
    <li><a href="#">Quản trị kho</a></li>
    <li class="active"><a href="#">Thêm mới hàng hóa</a></li>
}
@section jsFooter{
    <script>
        $('#TonToiThieu, #TonToiDa,#GiaNhapVe,#GiaBanLe,#GiaBanSi').keyup(function (event) {
            if (event.which >= 37 && event.which <= 40) return;
            this.value = this.value.replace(/\D/g, '')
                                   .replace(/\B(?=(\d{3})+(?!\d))/g, ',');
        });
        $('#TonToiThieu').val(0);
        $('#TonToiDa').val(0);
        $('#GiaNhapVe').val(0);
        $('#GiaBanLe').val(0);
        $('#GiaBanSi').val(0);
        $('#ThueSuat').val(10);
        $('#btnSelectImage').on('click', function (e) {
            e.preventDefault();
            var finder = new CKFinder();
            finder.selectActionFunction = function (url) {
                $('#txtImage').val(url);
            };
            finder.popup();
        });

        $('#btnSubmit').click(function () {
            $("#TonToiThieu").val($("#TonToiThieu").val().replace(/,/g, ''));
            $("#TonToiDa").val($("#TonToiDa").val().replace(/,/g, ''));
            $("#GiaNhapVe").val($("#GiaNhapVe").val().replace(/,/g, ''));
            $("#GiaBanLe").val($("#GiaBanLe").val().replace(/,/g, ''));
            $("#GiaBanSi").val($("#GiaBanSi").val().replace(/,/g, ''));
        });

        $('#AlertBox').removeClass('hide');
        $('#AlertBox').delay(1000).slideUp(500);
    </script>
}
<div class="panel panel-default">
    <div class="panel-heading">
        Thông tin hàng hóa
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
        @if (TempData["AlerMessage"] == null)
        {
            <div class="row">
                <div class="form-group">
                    <div id="AlertBox" class="alert @TempData["AlertType"] hide">
                        <h4>@TempData["AlertMessage"]</h4>
                    </div>
                </div>
            </div>
        }

        @using (Html.BeginForm("Create", "HangHoa", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    <label class="control-label col-md-2">Tên hàng hóa:</label>
                    <div class="col-md-4">
                        @Html.EditorFor(model => model.TenHH, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TenHH, "", new { @class = "text-danger" })
                    </div>
                    <label class="control-label col-md-2">Chủng loại:</label>
                    <div class="col-md-4">
                        @Html.DropDownListFor(model => model.LoaiMH, null, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.LoaiMH, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-2">Nước sản xuất:</label>
                    <div class="col-md-4">
                        @Html.DropDownListFor(model => model.NuocSXID, null, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.NuocSXID, "", new { @class = "text-danger" })
                    </div>
                    <label class="control-label col-md-2">Đơn vị tính:</label>
                    <div class="col-md-4">
                        @Html.DropDownListFor(model => model.DVT, null, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.DVT, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-2">Màu sắc:</label>
                    <div class="col-md-4">
                        @Html.DropDownListFor(model => model.MauID, null, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.MauID, "", new { @class = "text-danger" })
                    </div>
                    <label class="control-label col-md-2">Giá nhập về(VND):</label>
                    <div class="col-md-4">
                        @Html.TextBoxFor(model => model.GiaNhapVe, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.GiaNhapVe, "", new { @class = "text-danger" })
                    </div>

                </div>


                <div class="form-group">
                    <label class="control-label col-md-2">SL Tồn tối thiểu:</label>
                    <div class="col-md-4">
                        @Html.TextBoxFor(model => model.TonToiThieu, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.TonToiThieu, "", new { @class = "text-danger" })
                    </div>
                    <label class="control-label col-md-2">SL tồn tối đa:</label>
                    <div class="col-md-4">
                        @Html.TextBoxFor(model => model.TonToiDa, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.TonToiDa, "", new { @class = "text-danger" })
                    </div>

                </div>

                <div class="form-group">
                    <label class="control-label col-md-2">Giá bán lẻ(VND):</label>
                    <div class="col-md-4">
                        @Html.TextBoxFor(model => model.GiaBanLe, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.GiaBanLe, "", new { @class = "text-danger" })
                    </div>
                    <label class="control-label col-md-2">Giá bán sĩ(VND):</label>
                    <div class="col-md-4">
                        @Html.TextBoxFor(model => model.GiaBanSi, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.GiaBanSi, "", new { @class = "text-danger" })
                    </div>

                </div>


                <div class="form-group">
                    <label class="control-label col-md-2">Thuế suất (%):</label>
                    <div class="col-md-4">
                        @Html.EditorFor(model => model.ThueSuat, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ThueSuat, "", new { @class = "text-danger" })
                    </div>
                    <label class="control-label col-md-2">Ghi chú:</label>
                    <div class="col-md-4">
                        @Html.TextAreaFor(model => model.ThongTin, new { @class = "form-control", @row = 3 })
                        @Html.ValidationMessageFor(model => model.ThongTin, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-2">Ảnh minh họa:</label>
                    <div class="col-md-4">
                        @Html.TextBoxFor(model => model.Anh, new { id = "txtImage", @class = "form-control" })
                        <a href="#" class="btn btn-info" id="btnSelectImage">Chọn ảnh</a>
                        @Html.ValidationMessageFor(model => model.Anh, "", new { @class = "text-danger" })
                    </div>
                    <label class="control-label col-md-2">Cho phép tồn kho?</label>
                    <div class="col-md-4">
                        <div class="checkbox">
                            @Html.CheckBoxFor(model => model.TinhTonKho, new { @checked = "checked" })
                            @Html.ValidationMessageFor(model => model.TinhTonKho, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-4">
                        <input type="submit" id="btnSubmit" value="Tạo mới" class="btn btn-success" />
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Trở về", "Index")
        </div>
    </div>
    <!-- /.panel-body -->
</div>

HTHAplication/Areas/Admin/Views/HangHoa/Edit.cshtml
@model Models.EF.HangHoa
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
@section header{
    <li><a href="#">Quản trị kho</a></li>
    <li class="active"><a href="#">Thêm mới hàng hóa</a></li>
}
@section jsFooter{
    <script>
        $('#TonToiThieu').val($("#TonToiThieu").val().replace(/\B(?=(\d{3})+(?!\d))/g, ','));
        $('#TonToiDa').val($("#TonToiDa").val().replace(/\B(?=(\d{3})+(?!\d))/g, ','));
        $('#TonToiDa').val($("#TonToiDa").val().replace(/\B(?=(\d{3})+(?!\d))/g, ','));
        $('#GiaNhapVe').val($("#GiaNhapVe").val().replace(/\B(?=(\d{3})+(?!\d))/g, ','));
        $('#GiaBanLe').val($("#GiaBanLe").val().replace(/\B(?=(\d{3})+(?!\d))/g, ','));
        $('#GiaBanSi').val($("#GiaBanSi").val().replace(/\B(?=(\d{3})+(?!\d))/g, ','));
        $('#TonToiThieu, #TonToiDa,#GiaNhapVe,#GiaBanLe,#GiaBanSi').keyup(function (event) {
            if (event.which >= 37 && event.which <= 40) return;
            this.value = this.value.replace(/\D/g, '')
                                   .replace(/\B(?=(\d{3})+(?!\d))/g, ',');
        });        
        $('#btnSelectImage').on('click', function (e) {
            e.preventDefault();
            var finder = new CKFinder();
            finder.selectActionFunction = function (url) {
                $('#txtImage').val(url);
            };
            finder.popup();
        });

        $('#btnSubmit').click(function () {
            $("#TonToiThieu").val($("#TonToiThieu").val().replace(/,/g, ''));
            $("#TonToiDa").val($("#TonToiDa").val().replace(/,/g, ''));
            $("#GiaNhapVe").val($("#GiaNhapVe").val().replace(/,/g, ''));
            $("#GiaBanLe").val($("#GiaBanLe").val().replace(/,/g, ''));
            $("#GiaBanSi").val($("#GiaBanSi").val().replace(/,/g, ''));
        });

        $('#AlertBox').removeClass('hide');
        $('#AlertBox').delay(1000).slideUp(500);
    </script>
}
<div class="panel panel-primary">
    <div class="panel-heading">
        Thông tin hàng hóa
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
        @if (TempData["AlerMessage"] == null)
        {
            <div class="row">
                <div class="form-group">
                    <div id="AlertBox" class="alert @TempData["AlertType"] hide">
                        <h4>@TempData["AlertMessage"]</h4>
                    </div>
                </div>
            </div>
        }

        @using (Html.BeginForm("Edit", "HangHoa", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.MaHH)
                <div class="form-group">
                    <label class="control-label col-md-2">Tên hàng hóa:</label>
                    <div class="col-md-4">
                        @Html.EditorFor(model => model.TenHH, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TenHH, "", new { @class = "text-danger" })
                    </div>
                    <label class="control-label col-md-2">Chủng loại:</label>
                    <div class="col-md-4">
                        @Html.DropDownListFor(model => model.LoaiMH, null, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.LoaiMH, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-2">Nước sản xuất:</label>
                    <div class="col-md-4">
                        @Html.DropDownListFor(model => model.NuocSXID, null, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.NuocSXID, "", new { @class = "text-danger" })
                    </div>
                    <label class="control-label col-md-2">Đơn vị tính:</label>
                    <div class="col-md-4">
                        @Html.DropDownListFor(model => model.DVT, null, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.DVT, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-2">Màu sắc:</label>
                    <div class="col-md-4">
                        @Html.DropDownListFor(model => model.MauID, null, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.MauID, "", new { @class = "text-danger" })
                    </div>
                    <label class="control-label col-md-2">Giá nhập về(VND):</label>
                    <div class="col-md-4">
                        @Html.TextBoxFor(model => model.GiaNhapVe, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.GiaNhapVe, "", new { @class = "text-danger" })
                    </div>

                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">SL Tồn tối thiểu:</label>
                    <div class="col-md-4">
                        @Html.TextBoxFor(model => model.TonToiThieu, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.TonToiThieu, "", new { @class = "text-danger" })
                    </div>
                    <label class="control-label col-md-2">SL tồn tối đa:</label>
                    <div class="col-md-4">
                        @Html.TextBoxFor(model => model.TonToiDa, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.TonToiDa, "", new { @class = "text-danger" })
                    </div>

                </div>

                <div class="form-group">
                    <label class="control-label col-md-2">Giá bán lẻ(VND):</label>
                    <div class="col-md-4">
                        @Html.TextBoxFor(model => model.GiaBanLe, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.GiaBanLe, "", new { @class = "text-danger" })
                    </div>
                    <label class="control-label col-md-2">Giá bán sĩ(VND):</label>
                    <div class="col-md-4">
                        @Html.TextBoxFor(model => model.GiaBanSi, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.GiaBanSi, "", new { @class = "text-danger" })
                    </div>

                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">Thuế suất (%):</label>
                    <div class="col-md-4">
                        @Html.EditorFor(model => model.ThueSuat, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ThueSuat, "", new { @class = "text-danger" })
                    </div>
                    <label class="control-label col-md-2">Ghi chú:</label>
                    <div class="col-md-4">
                        @Html.TextAreaFor(model => model.ThongTin, new { @class = "form-control", @row = 3 })
                        @Html.ValidationMessageFor(model => model.ThongTin, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">Ảnh minh họa:</label>
                    <div class="col-md-4">
                        @Html.TextBoxFor(model => model.Anh, new { id = "txtImage", @class = "form-control" })
                        <a href="#" class="btn btn-info" id="btnSelectImage">Chọn ảnh</a>
                        @Html.ValidationMessageFor(model => model.Anh, "", new { @class = "text-danger" })
                    </div>
                    <label class="control-label col-md-2">Cho phép tồn kho?</label>
                    <div class="col-md-4">
                        <div class="checkbox">
                            @Html.CheckBoxFor(model => model.TinhTonKho, new { @checked = "checked" })
                            @Html.ValidationMessageFor(model => model.TinhTonKho, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-4">
                        <input type="submit" id="btnSubmit" value="Cập nhật" class="btn btn-success" />
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Trở về", "Index")
        </div>
    </div>
    <!-- /.panel-body -->
</div>

HTHAplication/Areas/Admin/Views/HangHoa/Index.cshtml
@model PagedList.IPagedList<Models.EF.HangHoa>
@using PagedList.Mvc;
@using HTHAplication.Common;
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
@section header{
    <li><a href="#">Quản trị kho</a></li>
    <li class="active"><a href="#">Danh sách hàng hóa</a></li>
}
@section jsFooter{

}
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
<script>
    $(document).ready(function () {
        $('#btn-refresh').click(function () {
            $('#txtSearch').val('');
        });
    });
</script>
<div id="wrapper">
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    Danh sách hàng hóa
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <form class="form-inline">
                        <div class="form-group">
                            <a href="@Url.Action("Create", "HangHoa")" class="btn btn-success">Thêm mới</a>
                            @using (Html.BeginForm("Index", "HangHoa", FormMethod.Get))
                            {
                                <input class="form-control" id="txtSearch" name="masp" value="@ViewBag.masp" placeholder="Gõ sản phẩm cần tìm" type="text">
                                <button type="submit" class="btn btn-info">Tìm kiếm</button>
                                <button type="submit" id="btn-refresh" class="btn btn-primary">Làm mới</button>
                            }
                        </div>
                    </form>
                    <br />
                    <div class="row">
                        @foreach (var item in Model)
                        {
                            <div id="row_@item.MaHH" class="col-sm-4">
                                <div class="product">
                                    <div class="image-product">
                                        <img src="@item.Anh">
                                        <br /><br />
                                        <span class="badge">
                                            SL:
                                            @(item.SoLuong.HasValue ? item.SoLuong.Value.ToString("N0") : "0")
                                        </span>
                                    </div>
                                    <div class="infor-product">
                                        <a href="#" data-toggle="tooltip" title="@item.TenHH">
                                            @(item.TenHH.Length > 24 ? (item.TenHH.Substring(0, 24) + "...") : item.TenHH)
                                        </a>
                                        <br />
                                        Mã hàng:<span>@item.MaHH</span><br />
                                        Giá lẻ:<span>
                                            @(item.GiaBanLe.HasValue ? (item.GiaBanLe.Value.ToString("N0") + " VND") : "Liên hệ")
                                        </span><br />
                                        <a href="@Url.Action("Edit", "HangHoa", new { id = item.MaHH })" class="btn btn-info">Chi tiết</a>

                                        @Ajax.ActionLink("Xoá", "Delete", new { @id = item.MaHH }, new AjaxOptions
                                        {
                                            Confirm = "Bạn có muốn xoá bản ghi này?",
                                            OnComplete = "$('#row_" + @item.MaHH + "').remove()",
                                            HttpMethod = "Delete"
                                        }, new { @class = "btn btn-danger" })

                                    </div>
                                </div>
                            </div>
                        }

                    </div>
                    <div class="clearfix"></div>
                    <div class="col-xs-12">
                        Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) của @Model.PageCount
                        @Html.PagedListPager(Model, page => Url.Action("Index", new { page, @masp = @ViewBag.masp }))
                    </div>
                </div>

            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->

    </div>
</div>