HTHAplication/Areas/Admin/Controllers/LoaiMatHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Models.Dao;
using Models.EF;
namespace HTHAplication.Areas.Admin.Controllers
{
    public class LoaiMatHangController : BaseController
    {
        // GET: Admin/LoaiMatHang
        public ActionResult Index()
        {
            var dao = new LoaiMatHangDao();
            var model = dao.ListAll();
            return View(model);
        }
        public ActionResult Create()
        {
            return View();
        }
        public ActionResult Edit(string id)
        {
            var dao =new LoaiMatHangDao();
            var model = dao.GetByID(id);
            return View(model);
        }
        [HttpPost]
        public ActionResult Create(LoaiMatHang entity)
        {
            if (ModelState.IsValid)
            {
                var dao = new LoaiMatHangDao();
                if (dao.Insert(entity))
                {
                    SetAlert("Thêm thành công!", "success");
                }
                else
                {
                    SetAlert("Lỗi thêm hàng hóa!", "error");
                }
            }
            else
            {
                SetAlert("Lỗi thêm hàng hóa!", "error");
            }
            return View();
        }
        [HttpPost]
        public ActionResult Edit(LoaiMatHang entity)
        {
            if (ModelState.IsValid)
            {
                var dao = new LoaiMatHangDao();
               if (dao.Update(entity))
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    SetAlert("Lỗi cập nhật chủng loại!", "error");
                    return View(entity);
                }
            }
            else
            {
                SetAlert("Lỗi cập nhật chủng loại!", "error");
                return View(entity);
            }
            
        }
        [HttpDelete]
        public ActionResult Delete(string id)
        {
            var dao = new LoaiMatHangDao();
            var model = dao.GetByID(id);
            if (model != null)
            {
                dao.Delete(model);
            }
            return RedirectToAction("Index");
        }
    }
}

HTHAplication/Areas/Admin/Views/LoaiMatHang/Create.cshtml
@model Models.EF.LoaiMatHang

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@section header{
    <li><a href="#">Quản trị kho</a></li>
    <li class="active"><a href="#">Thêm mới chủng loại</a></li>
}
@section jsFooter{
<script>
    $('#AlertBox').removeClass('hide');
    $('#AlertBox').delay(1000).slideUp(500);
</script>
}
<div class="panel panel-default">
    <div class="panel-heading">
        Thông tin về chủng loại
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
        @if (TempData["AlerMessage"] == null)
        {
            <div class="row">
                <div class="form-group">
                    <div id="AlertBox" class="alert @TempData["AlertType"] hide">
                        <h4>@TempData["AlertMessage"]</h4>
                    </div>
                </div>
            </div>
        }
        
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    <label class="control-label col-md-2">Mã chủng loại:</label>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ID, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-2">Tên chủng loại:</label>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Ten, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Ten, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Thêm mới" class="btn btn-success" />
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Trở về", "Index")
        </div>
    </div>
</div>

HTHAplication/Areas/Admin/Views/LoaiMatHang/Edit.cshtml
@model Models.EF.LoaiMatHang

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@section header{
    <li><a href="#">Quản trị kho</a></li>
    <li class="active"><a href="#">Loại mặt hàng</a></li>
}
<div id="wrapper">
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    Cập nhật thông tin cho mã chủng loại:@((Model.ID != null) ? @Model.ID : "")
                </div>
                @if (TempData["AlerMessage"] == null)
                {
                    <div class="row">
                        <div class="form-group">
                            <div id="AlertBox" class="alert @TempData["AlertType"] hide">
                                <h4>@TempData["AlertMessage"]</h4>
                            </div>
                        </div>
                    </div>
                }
                <!-- /.panel-heading -->
                <div class="panel-body">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()
                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.ID)

                            <div class="form-group">
                                <label class="control-label col-md-2">Tên chủng loại:</label>
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Ten, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Ten, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Save" class="btn btn-success" />
                                </div>
                            </div>
                        </div>
                    }

                    <div>
                        @Html.ActionLink("Trở về", "Index")
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

HTHAplication/Areas/Admin/Views/LoaiMatHang/Index.cshtml
@model IEnumerable<Models.EF.LoaiMatHang>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@section header{
    <li><a href="#">Quản trị kho</a></li>
    <li class="active"><a href="#">Loại mặt hàng</a></li>
}
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
<div id="wrapper">
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    Danh sách chủng loại hàng hóa
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <p>
                        <a href="@Url.Action("Create", "LoaiMatHang")" class="btn btn-success">Thêm mới</a>
                    </p>
                    <table class="table">
                        <tr>
                            <th>
                                Tên
                            </th>                           
                            <th>Hành động</th>
                        </tr>

                        @foreach (var item in Model)
                        {
                            <tr id="row_@item.ID">
                                <td>
                                    @Html.DisplayFor(modelItem => item.Ten)
                                </td>                               
                                <td>
                                    @Html.ActionLink("Sửa", "Edit", new { id = item.ID }, new { @class="btn btn-info"}) |
                                    @Ajax.ActionLink("Xoá", "Delete", new { @id = item.ID }, new AjaxOptions
                                        {
                                            Confirm = "Bạn có muốn xoá bản ghi này?",
                                            OnComplete = "$('#row_" + @item.ID + "').remove()",
                                            HttpMethod = "Delete"
                                        }, new { @class = "btn btn-danger" })
                                </td>
                            </tr>
                        }

                    </table>
                </div>
            </div>
        </div>
    </div>
</div>